Repository team-MiniJin/BE, pull requests merged in 2024-06, with the labels that each got.

#36 Feature/local join
  src/main/java/com/minizin/travel/config/SecurityConfig.java
  src/main/java/com/minizin/travel/user/controller/AuthController.java
  src/main/java/com/minizin/travel/user/domain/dto/JoinDto.java
  src/main/java/com/minizin/travel/user/domain/entity/UserEntity.java
  src/main/java/com/minizin/travel/user/domain/repository/UserRepository.java
  src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/minizin/travel/user/service/AuthService.java
  src/test/java/com/minizin/travel/user/service/AuthServiceTest.java
Labels: feature

#45 feat:✨ #44 add feature calculate plan budget
  src/main/java/com/minizin/travel/plan/dto/ListPlanDto.java
  src/main/java/com/minizin/travel/plan/service/PlanService.java
Labels: feature

#64 fix:🐛 delete budget field in test
  src/test/java/com/minizin/travel/plan/CreatePlanTest.java
Labels: bug

#60 Feature/mail/auth-code
  build.gradle
  src/main/java/com/minizin/travel/config/JasyptConfig.java
  src/main/java/com/minizin/travel/config/MailConfig.java
  src/main/java/com/minizin/travel/config/RedisConfig.java
  src/main/java/com/minizin/travel/config/SecurityConfig.java
  src/main/java/com/minizin/travel/user/controller/MailController.java
  src/main/java/com/minizin/travel/user/domain/dto/SendMailDto.java
  src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/minizin/travel/user/service/MailService.java
  src/main/java/com/minizin/travel/user/service/RedisService.java
  src/main/resources/application.yml
  src/main/resources/templates/mailForm.html
  src/test/java/com/minizin/travel/config/JasyptConfigTest.java
Labels: feature

#66 feat:✨ #39 'select upcoming plan'
  src/main/java/com/minizin/travel/plan/controller/PlanController.java
  src/main/java/com/minizin/travel/plan/dto/UpcomingPlanDto.java
  src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
  src/main/java/com/minizin/travel/plan/service/PlanService.java
Labels: feature

#116 refactor:♻ TourController,Service more simply code modified with asynchronous method.
  src/main/java/com/minizin/travel/tour/controller/TourController.java
  src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
  src/main/java/com/minizin/travel/tour/domain/entity/TourAPI.java
  src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
  src/main/java/com/minizin/travel/tour/service/TourInfoService.java
  src/main/java/com/minizin/travel/tour/service/TourService.java
Labels: refactor

#140 feat:✨api-tour searchKeyword1 GET Service finished
  src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
  src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
  src/main/java/com/minizin/travel/tour/service/TourInfoService.java
Labels: feature

#165 feat:✨api-tour detail Common GET Service,controller
  src/main/java/com/minizin/travel/tour/controller/TourController.java
  src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
  src/main/java/com/minizin/travel/tour/domain/entity/TourAPI.java
  src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
  src/main/java/com/minizin/travel/tour/service/TourInfoService.java
  src/main/java/com/minizin/travel/tour/service/TourService.java
Labels: feature

#181 refactor:♻ api-tour : Error 핸들링 & detail common save방식 -> save All 방식
  src/main/java/com/minizin/travel/tour/controller/TourController.java
  src/main/java/com/minizin/travel/tour/service/TourService.java
Labels: refactor

#204 fix:🐛 api-tour sigungucode만 가져오는 코드 완성
  src/main/java/com/minizin/travel/tour/controller/TourController.java
  src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
  src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
  src/main/java/com/minizin/travel/tour/service/TourInfoService.java
  src/main/java/com/minizin/travel/tour/service/TourService.java
Labels: bug
